version: "2"

linters:
  enable:
    - errcheck
    - ineffassign
    - misspell
    - unconvert
    - unparam
  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - errcheck
      - text: "exported:"
        linters:
          - revive
      - text: "should have comment"
        linters:
          - revive
      - linters:
          - staticcheck
        text: "ST1000"
run:
  timeout: 5m
