linters:
  enable:
    - errcheck
    - ineffassign
    - misspell
    - unconvert
    - unparam
issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - errcheck
  exclude:
    - "exported:"
    - "should have comment"
    - "ST1000"
run:
  timeout: 5m
